### ISSUE TITLE
Server connection between the bot and the server ?

### ISSUE THREAD

**Issue by Sarbatore** [X-rays5/Fivem-discord-rpc-and-player-count-bot#2]
How to install it ? Help please

**Comment by X-rays5** [comment]
Hi,
thank you for creating a issue I have updated the readme with a install guide
https://github.com/X-rays5/Fivem-discord-rpc-and-player-count-bot/blob/master/README.md

**Comment by Sarbatore** [comment]
> what is the issue exactly? Is there a error in the console?

I didn't try because I don't understand how does int work. Because I'm hosting my bot on a host, not the same of my server.

**Comment by X-rays5** [comment]
it's a resource for the server. So when the server starts it will create a instance of the discord bot and update it's status to the player count. Just like any other resource. And when a player joins the server it will start discord rpc for that user.
It will then show on the players discord. The server name playername and playercount.

**Comment by X-rays5** [comment]
yeah just add the this as a resource and the bot will start with the server

**Comment by Sarbatore** [comment]
I have some problems so:

nfo No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...

error Couldn't find package "ws@^7.3.1" required by "discord.js@github:vecchiotom/discord.js" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Building resource discord-npc-count failed.
Error data: yarn failed!

**Comment by X-rays5** [comment]
cd into the folder and then type npm i in the console
